/** 未分配利润 */
const SPECIAL_FUNDS_FIRST = 'WFPLR'
/** 折旧（更改） */
const SPECIAL_FUNDS_SECOND = 'ZJGG'
/** 井巷工程费 */
const SPECIAL_FUNDS_THIRD = 'JXGCF'
/** 维简费 */
const SPECIAL_FUNDS_FOURTH = 'WJF'
/** 煤炭安全资金 */
const SPECIAL_FUNDS_FIFTH = 'MTAQZJ'
/** 环境治理保证金 */
const SPECIAL_FUNDS_SIXTH = 'HJZLBZJ'
/** 危化品安全资金 */
const SPECIAL_FUNDS_SEVENTH = 'WHPAQZJ'

/** 股东助资 */
const CONSTRUCTION_FUNDS_FIRST = 'GDZZ'
/** 政府补助 */
const CONSTRUCTION_FUNDS_SECOND = 'ZFZZ'
/** 项目借款 */
const CONSTRUCTION_FUNDS_THIRD = 'XMJK'

export const capitalSourceShortNameList = [SPECIAL_FUNDS_FIRST, SPECIAL_FUNDS_SECOND, SPECIAL_FUNDS_THIRD, SPECIAL_FUNDS_FOURTH, SPECIAL_FUNDS_FIFTH, SPECIAL_FUNDS_SIXTH, SPECIAL_FUNDS_SEVENTH, CONSTRUCTION_FUNDS_FIRST, CONSTRUCTION_FUNDS_SECOND, CONSTRUCTION_FUNDS_THIRD]
