package com.appmf.net.appmf.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AD_STATISTICS_MODEL".
*/
public class AdStatisticsModelDao extends AbstractDao<AdStatisticsModel, String> {

    public static final String TABLENAME = "AD_STATISTICS_MODEL";

    /**
     * Properties of entity AdStatisticsModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Click = new Property(1, long.class, "click", false, "CLICK");
        public final static Property Shows = new Property(2, long.class, "shows", false, "SHOWS");
        public final static Property End_time = new Property(3, long.class, "end_time", false, "END_TIME");
        public final static Property Time = new Property(4, long.class, "time", false, "TIME");
    }


    public AdStatisticsModelDao(DaoConfig config) {
        super(config);
    }
    
    public AdStatisticsModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AD_STATISTICS_MODEL\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"CLICK\" INTEGER NOT NULL ," + // 1: click
                "\"SHOWS\" INTEGER NOT NULL ," + // 2: shows
                "\"END_TIME\" INTEGER NOT NULL ," + // 3: end_time
                "\"TIME\" INTEGER NOT NULL );"); // 4: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AD_STATISTICS_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AdStatisticsModel entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getClick());
        stmt.bindLong(3, entity.getShows());
        stmt.bindLong(4, entity.getEnd_time());
        stmt.bindLong(5, entity.getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AdStatisticsModel entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getClick());
        stmt.bindLong(3, entity.getShows());
        stmt.bindLong(4, entity.getEnd_time());
        stmt.bindLong(5, entity.getTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public AdStatisticsModel readEntity(Cursor cursor, int offset) {
        AdStatisticsModel entity = new AdStatisticsModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getLong(offset + 1), // click
            cursor.getLong(offset + 2), // shows
            cursor.getLong(offset + 3), // end_time
            cursor.getLong(offset + 4) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AdStatisticsModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setClick(cursor.getLong(offset + 1));
        entity.setShows(cursor.getLong(offset + 2));
        entity.setEnd_time(cursor.getLong(offset + 3));
        entity.setTime(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(AdStatisticsModel entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(AdStatisticsModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AdStatisticsModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
